spring:
<<<<<<< HEAD
jpa:
show-sql: true
properties:
hibernate:
format_sql: true
=======
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
>>>>>>> e552e56 (ajustando applications)
